// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class CoffeeHerosResources
{
        public const string achievement_slayer = "CgkI3YfUyK4SEAIQCw"; // <GPGSID>
        public const string achievement_champion = "CgkI3YfUyK4SEAIQBA"; // <GPGSID>
        public const string achievement_wage_earner = "CgkI3YfUyK4SEAIQBg"; // <GPGSID>
        public const string achievement_money_maker = "CgkI3YfUyK4SEAIQBw"; // <GPGSID>
        public const string achievement_executioner = "CgkI3YfUyK4SEAIQCQ"; // <GPGSID>
        public const string leaderboard_distance = "CgkI3YfUyK4SEAIQAQ"; // <GPGSID>
        public const string achievement_well_heeled = "CgkI3YfUyK4SEAIQCA"; // <GPGSID>
        public const string achievement_no_mercy = "CgkI3YfUyK4SEAIQCg"; // <GPGSID>
        public const string achievement_savior = "CgkI3YfUyK4SEAIQAw"; // <GPGSID>
        public const string achievement_novice = "CgkI3YfUyK4SEAIQAg"; // <GPGSID>
        public const string achievement_cheater = "CgkI3YfUyK4SEAIQBQ"; // <GPGSID>

}

